In [1]:
from datasets import load_dataset
import pandas as pd

/home/mp/anaconda3/envs/mlops/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [45]:
df = pd.read_csv('data/processed/AITA-Reddit-Dataset.csv')

In [46]:
df

                                                     text  ESH  NAH  NTA  YTA
0       i turned 30 on monday. i don't have a problem ...  0.0  0.0  1.0  0.0
1       feed up with my gf. for 6 years ive supported ...  0.0  0.0  1.0  0.0
2        so at the start of the school year. like any ...  0.0  0.0  1.0  0.0
3       sorry for format, using mobile. so a little bi...  0.0  0.0  1.0  0.0
4       so next week is finals week at my university a...  0.0  0.0  1.0  0.0
...                                                   ...  ...  ...  ...  ...
270704  my great grandma gigi, ran a business back in ...  0.0  0.0  1.0  0.0
270705  so my (15f) birthday was a few days ago and my...  0.0  0.0  1.0  0.0
270706  i have already posted this story but now i’m p...  0.0  0.0  1.0  0.0
270707  character line-up: me (32f), and my girlfriend...  0.0  0.0  0.0  1.0
270708  for some context, i had a baby in january. cra...  0.0  0.0  1.0  0.0

[270709 rows x 5 columns]

In [10]:
dataset = load_dataset("OsamaBsher/AITA-Reddit-Dataset")

In [3]:
train_dataset = dataset['train']
train_df = train_dataset.to_pandas()
train_df.to_csv('data/processed/AITA-Reddit-Dataset.csv', index=False)

In [11]:
df = pd.read_csv('data/raw/AITA-Reddit-Dataset.csv')

In [12]:
new_df = df[["text","verdict"]]

In [ ]:
# NTA : Not the asshole
# YTA : You're the asshole
# NAH : No assholes here
# ESH : Everyone sucks here

In [13]:
new_df['verdict'].value_counts()

verdict
nta    203079
yta     47408
nah     13342
esh      6880
Name: count, dtype: int64

In [14]:
df

,id,title,text,verdict,comment1,comment2,score
0,4pcrle,aita for wanting to celebrate my birthday,i turned 30 on monday. i don't have a problem ...,nta,"i think you know your nta, it seems like you j...",definitely nta. i suffer from depression and a...,15
1,89o0sd,aita for being,feed up with my gf. for 6 years ive supported ...,nta,"nta dude, call a hotline and report her, then ...",nta. i would quite literally lose my mind in y...,63
2,8d5qpg,aita for getting mad at an autistic kid?,so at the start of the school year. like any ...,nta,it's tough but no you're nta. you are not trai...,nta. my brother is autistic and i love him to ...,329
3,8f40sm,aita for playing a prank on my housemates?,"sorry for format, using mobile. so a little bi...",nta,nta getting mad over walking up some stairs is...,"not the most genius prank ever concocted, but ...",70
4,8hh8q7,aita for asking my boyfriend to not be in the ...,so next week is finals week at my university a...,nta,nta. i ask my boyfriend to leave the room when...,nta. that’s ridiculous. there’s no reason he s...,18
...,...,...,...,...,...,...,...
270704,128nxuw,aita for not asking family to restart business.,"my great grandma gigi, ran a business back in ...",nta,nta. nobody wanted the business or brand until...,"nta but, you better trademark the name before ...",12
270705,128o0cg,aita for not buying my brother a game with my ...,so my (15f) birthday was a few days ago and my...,nta,nta. why should you spend your birthday money ...,of course nta sweetie! your brother is an adul...,23
270706,128o12x,wibta if i take my mother to court over my col...,i have already posted this story but now i’m p...,nta,"nta - just so i understand, your late grandfat...",110% nta. you need to act quickly to protect ...,708
270707,128o5ag,aita for refusing to kiss my girlfriend after ...,"character line-up: me (32f), and my girlfriend...",yta,hmmm. i’m sorry- but i’m going very soft yta. ...,french kiss and a kiss is totally different on...,0
270708,128o5aw,aita for visiting my parents with my newborn,"for some context, i had a baby in january. cra...",nta,nta. go anyway. you have every right to visit ...,stop talking to your sister about this. it’s n...,153

In [38]:
df['verdict'].where(df['verdict'] == 'nah').dropna()

1667      nah
1714      nah
1717      nah
1730      nah
1764      nah
         ...
270487    nah
270504    nah
270509    nah
270558    nah
270629    nah
Name: verdict, Length: 13342, dtype: object

In [39]:
df['text'].iloc[1667]

'i\'m annoyed. this morning my (half) sister dramatically busted into the garage while i was smoking a cigarette. she walks up to me and asks in an accusatory manner"do you own a sprint wireless or comcast account?". i reply, "no, why?". i\'m totally oblivious to what\'s going on. she then says, "well, i don\'t know where these charges came from, it\'s one for $200 and another for $370".  we go back in the house and i start heating up some food in the microwave. i tell her she probably has a fraudulent charge and should contact her bank. i explain to her comcast isn\'t even available in our area,  internet service is limited to spectrum (formerly time warner) or atnt. it obviously must be a charge from outside our area, andwhy would she even ask me? she ignores the question. she then proceeds to complain about how this is disrupting her morning and she needs to go back to the bank. she rushes out the house slamming the door behind her. background:  i\'ve been staying with my sister for about two months since my husband and i have been separated. i\'m a 25 year old young professional with a two year old daughter. i have a decent job doing web content management and graphic design. i\'ve been paying rent to her on time, i contribute a share of groceries for the house, and do a fair share of chores. my husband and i are attending marriage counseling to work on things, but i\'m preparing myself for the possibility of being a single parent if it doesn\'t. my sister and i have the same dad. he\'s white. my mom is black. her mom is white. there are some cultural differences and perspectives that are generally accepted by both of us, and we otherwise get along fine. she\'s 42. i don\'t understand why she would immediately confront me about account charges that are obviously bogus.  i believe it may be some underlying racial bias.  plus, i\'m not a thief. i even buy my own laundry soap, toiletries, etc. i don\'t use any of her stuff. we drink beer together, i\'ll buy a case, she\'ll buy a case. occasionally bum cigarettes from one other if we\'re out (i know gross habit i should quit). i\'m pissed. it\'s like, really? she asks me before she contacts her bank. i have no history of theft or criminal behavior. no drug abuse or addiction. we both smoke pot, but whatever. why would she immediately ask me about hacking her fucking bank account? aita if i confront her about my feelings when she gets back?  aita if i tell her i think she confronted me based on racial bias, whether it was conscious or not, and that\'s not ok? tldr - my (25f) sister (42f), who i am staying with temporarily, confronts me about fraudulent charges on her account that i have zero knowledge of. i\'m pissed, because the only reason i feel she would have for questioning me must be racially biased. i want to know aita if i call her out and express my feelings truthfully. '

In [26]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ('Text', 'passthrough', ['text']),
        ('Verdict', OneHotEncoder(), ['verdict'])
    ])

processed = preprocessor.fit_transform(df[['text','verdict']])

In [43]:
final_df = pd.DataFrame(processed, columns=['text','ESH','NAH','NTA','YTA'])

In [44]:
final_df

                                                     text  ESH  NAH  NTA  YTA
0       i turned 30 on monday. i don't have a problem ...  0.0  0.0  1.0  0.0
1       feed up with my gf. for 6 years ive supported ...  0.0  0.0  1.0  0.0
2        so at the start of the school year. like any ...  0.0  0.0  1.0  0.0
3       sorry for format, using mobile. so a little bi...  0.0  0.0  1.0  0.0
4       so next week is finals week at my university a...  0.0  0.0  1.0  0.0
...                                                   ...  ...  ...  ...  ...
270704  my great grandma gigi, ran a business back in ...  0.0  0.0  1.0  0.0
270705  so my (15f) birthday was a few days ago and my...  0.0  0.0  1.0  0.0
270706  i have already posted this story but now i’m p...  0.0  0.0  1.0  0.0
270707  character line-up: me (32f), and my girlfriend...  0.0  0.0  0.0  1.0
270708  for some context, i had a baby in january. cra...  0.0  0.0  1.0  0.0

[270709 rows x 5 columns]